language: java
jdk:
  - openjdk7
  - oraclejdk7
install: "travis_retry mvn install -DskipTests=true -Pintegration-tests -B -V"
script: "travis_retry mvn verify -Pintegration-tests -B -V"
env: MAVEN_OPTS="-XX:MaxPermSize=128m"

