language: java
jdk:
  - openjdk7
  - oraclejdk7
install: "mvn install -DskipTests=true -Pintegration-tests -B -V"
script: "mvn verify -Pintegration-tests -B -V"
env: MAVEN_OPTS="-XX:MaxPermSize=128m"

